### ISSUE TITLE
Dnsmasq does not work if consul_client_address used

### ISSUE THREAD

**Issue by williamoneill** [jivesoftware/ansible-consul#61]
First, thanks for all of this. I'm new to Consul and this project helped me a lot.

When I set consul_client_address, I found that Dnsmasq no longer works. The problem is that 127.0.0.1 is hard-coded in dnsmasq.yml.

I fixed it by changing the line to this:
    content='server=/{{ consul_domain }}/{{ consul_client_address }}#{{ consul_port_dns }}'

The various client addresses can be individually configured using the config file (https://www.consul.io/docs/agent/options.html) and the *addresses* object. I'm sure you know this. I don't know if you want to be able to set all the addresses individually in this project. 

Thanks again for all of your work. This has been a huge help.

**Comment by trumant** [comment]
@williamoneill - Nice catch! I'll have a fix PRed in a bit.

**Comment by MrMMorris** [comment]
@williamoneill what were you setting `client_addr` to that made dnsmasq not work? I have noticed that when I set it to `0.0.0.0` and dnsmasq is also set to that, dns lookups are broken until I set dnsmasq to `127.0.0.1`

**Comment by MrMMorris** [comment]
After some testing, I can't even get my consul to work without setting `client_addr` to `0.0.0.0` and dns doesn't work in that instance unless the dnsmasq ip is `127.0.0.1`.

@williamoneill not sure what your setup is like, but it seems that we should check if `client_addr` is `0.0.0.0` and if so, keep the dnsmasq ip as `127.0.0.1`.

I also have a dns test, but I'm not sure if it would apply to all cases:

```yaml
- name: check dns
  command: dig {{ consul_node_name }}.node.consul
  register: dns_test
  notify:
    - test dns

- name: test dns
  fail: msg="Consul DNS not resolving properly"
  when: "'{{ ansible_eth0.ipv4.address }}' not in dns_test.stdout"
```
